### ISSUE TITLE
Update babel-minify to the latest beta version

### ISSUE THREAD

**Issue by pmdartus** [salesforce/observable-membrane#16]
### Description

We need to update `babel-minify` dependency to the latest beta version since `0.4.3` has some loop transformation issues.

https://github.com/salesforce/observable-membrane/blob/ce10e6dfc8ecc86be2014648f2f35d39178d9146/package.json#L39

**Comment by caridy** [comment]
@pmdartus any chance that you can get this one done?

**Comment by diervo** [comment]
I believe we want to use terser instead since minify its kind of unmaintained and its a very nasty bug pending that will take a long time to fix.
