### ISSUE TITLE
ReadOnly membrane doesn't throw when mutating a value on JavascriptCore

### ISSUE THREAD

**Issue by pmdartus** [salesforce/observable-membrane#28]
### Description

The following code snippet should throw even when `process.env.NODE_ENV` is set to `production` because the Proxy `set` handler [returns a `false`](https://github.com/salesforce/observable-membrane/blob/master/src/read-only-handler.ts#L40-L46). However JSC has a [known issue](https://bugs.webkit.org/show_bug.cgi?id=177398) where the Proxy doesn't throw a `TypeError` if the returned value is false.

```js
import ObservableMembrane from 'observable-membrane';

const membrane = new ObservableMembrane({
    valueObserved() {},
});

const foo = membrane.getReadOnlyProxy({ value: true });
foo.value = false;
// ^ JSC: throw an Error in dev, and do nothing in prod
// ^ Other engines: throw an Error in dev and a TypeError in prod
```

Based on the current documentation, the ReadOnly membrane should only throw in dev mode and not in prod mode. I would be advocating to return `true` in the `set` handler to provide a consistent experience and match with the expected behavior.

#### Browsers Affected
* Safari

#### Version
0.26.0

**Comment by caridy** [comment]
@pmdartus I'm fine with this. Want to send a PR?

**Comment by nolanlawson** [comment]
[The WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=177398) was fixed in 2019; can this issue be closed?

**Comment by pmdartus** [comment]
Yes, no need to keep this around.
